/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package app1;

/**
 *
 * @author x14110784
 */
public class appFrame extends javax.swing.JFrame {

    /**
     * Creates new form appFrame
     */
    public appFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBiology = new javax.swing.JButton();
        btnPhy = new javax.swing.JButton();
        btnChem = new javax.swing.JButton();
        btnMath = new javax.swing.JButton();
        txtFldMsg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(690, 445));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("HomePage");

        btnBiology.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app1/1425157271_microscope.png"))); // NOI18N
        btnBiology.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBiologyMouseMoved(evt);
            }
        });
        btnBiology.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBiologyMouseClicked(evt);
            }
        });
        btnBiology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBiologyActionPerformed(evt);
            }
        });

        btnPhy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app1/1425157704_atom.png"))); // NOI18N
        btnPhy.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnPhyMouseMoved(evt);
            }
        });
        btnPhy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPhyMouseClicked(evt);
            }
        });

        btnChem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app1/1425157553_allergy_vials.png"))); // NOI18N
        btnChem.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnChemMouseMoved(evt);
            }
        });
        btnChem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChemMouseClicked(evt);
            }
        });

        btnMath.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app1/math.png"))); // NOI18N
        btnMath.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnMathMouseMoved(evt);
            }
        });
        btnMath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMathMouseClicked(evt);
            }
        });

        txtFldMsg.setEditable(false);
        txtFldMsg.setBackground(new java.awt.Color(204, 204, 204));
        txtFldMsg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFldMsg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFldMsg.setBorder(null);
        txtFldMsg.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(273, 273, 273))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBiology, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPhy, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMath, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFldMsg)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBiology, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPhy))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnChem)
                        .addGap(18, 18, 18)
                        .addComponent(btnMath)))
                .addGap(18, 18, 18)
                .addComponent(txtFldMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBiologyMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBiologyMouseMoved
        txtFldMsg.setText("Biology");
    }//GEN-LAST:event_btnBiologyMouseMoved

    private void btnPhyMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhyMouseMoved
        txtFldMsg.setText("Physics");
    }//GEN-LAST:event_btnPhyMouseMoved

    private void btnChemMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChemMouseMoved
        txtFldMsg.setText("Chemistry");
    }//GEN-LAST:event_btnChemMouseMoved

    private void btnMathMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMathMouseMoved
        txtFldMsg.setText("Mathematics");
    }//GEN-LAST:event_btnMathMouseMoved

    private void btnBiologyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBiologyMouseClicked
        new Bio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBiologyMouseClicked

    private void btnPhyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhyMouseClicked
        new Physic().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPhyMouseClicked

    private void btnMathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMathMouseClicked
        new Math().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMathMouseClicked

    private void btnChemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChemMouseClicked
        new Chemist().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnChemMouseClicked

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        txtFldMsg.setText("");
    }//GEN-LAST:event_jPanel1MouseMoved

    private void btnBiologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBiologyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBiologyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBiology;
    private javax.swing.JButton btnChem;
    private javax.swing.JButton btnMath;
    private javax.swing.JButton btnPhy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtFldMsg;
    // End of variables declaration//GEN-END:variables
}
