/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package app1;

/**
 *
 * @author x14404242
 */
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class MQuiz extends javax.swing.JFrame {
    

//Declare arrays and variables
    private ArrayList <String> answer;
    private ArrayList <String> questions;
    private ArrayList <String> userAnswer;
    private ArrayList <Integer> marks;
    private int sum;
    private int total; 
    
    private String name;
    private String printableTotal;
    private int mark;
    private String subj;
    
    
    
   

    /**
     * Creates new form MQuiz
     */
    public MQuiz() {
        initComponents();
        
        subj = "Maths";
        name  = JOptionPane.showInputDialog("Please enter your name");
      
        //create arrays and assign values to variables
        //populate arrays
        
    
        answer=new ArrayList<>();
        questions=new ArrayList<>();
        userAnswer=new ArrayList<>();
        marks=new ArrayList<>();
        
        
        String q1 = "Q1: 2+2";
        String q2 ="Q2:5*5";
        String q3= "Q3:1+1";
        String q4= "Q4:11+1";
        String q5= "Q5:100+1";
        String q6= "Q6:1110+1";
        String q7= "Q7:12+1";
        
        String a1= "4";
        String a2= "25";
        String a3= "2";
        String a4= "12";
        String a5= "101";
        String a6= "1111";
        String a7= "13";
        
        questions.add(q1);
        questions.add(q2);
        questions.add(q3);
        questions.add(q4);
        questions.add(q5);
        questions.add(q6);
        questions.add(q7);
        
        answer.add(a1);
        answer.add(a2);
        answer.add(a3);
        answer.add(a4);
        answer.add(a5);
        answer.add(a6);
        answer.add(a7);
       
        question1.setText(questions.get(0));
        question2.setText(questions.get(1));
        question3.setText(questions.get(2));
        question4.setText(questions.get(3));
        question5.setText(questions.get(4));
        question6.setText(questions.get(5));
        question7.setText(questions.get(6));
        
        ans1.setText("");
        ans2.setText("");
        ans3.setText("");
        ans4.setText("");
        ans5.setText("");
        ans6.setText("");
        ans7.setText("");
                
        
        sum=0;
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mathsQuiz = new javax.swing.JPanel();
        mathsLabel = new javax.swing.JLabel();
        question1 = new javax.swing.JLabel();
        ans1 = new javax.swing.JTextField();
        question2 = new javax.swing.JLabel();
        ans2 = new javax.swing.JTextField();
        ans3 = new javax.swing.JTextField();
        question3 = new javax.swing.JLabel();
        ans4 = new javax.swing.JTextField();
        question4 = new javax.swing.JLabel();
        ans5 = new javax.swing.JTextField();
        question5 = new javax.swing.JLabel();
        question6 = new javax.swing.JLabel();
        ans6 = new javax.swing.JTextField();
        question7 = new javax.swing.JLabel();
        ans7 = new javax.swing.JTextField();
        revealbtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuReturn = new javax.swing.JMenuItem();
        mnuHome = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Math Quiz (Jade)");

        mathsLabel.setFont(new java.awt.Font("Tekton Pro", 2, 18)); // NOI18N
        mathsLabel.setForeground(new java.awt.Color(51, 255, 0));
        mathsLabel.setText("Math Quiz");

        question1.setText("Q1: 3*5=");

        ans1.setText("9569");
        ans1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans1ActionPerformed(evt);
            }
        });

        question2.setText("Q2: 2+2=");

        ans2.setText("995.5 * 3");

        ans3.setText("69");

        question3.setText("Q3: Maths Question + Math Question =");

        ans4.setText("100");

        question4.setText("Q4: Maths Question + Math Question =");

        ans5.setText(".2");

        question5.setText("Q5: Maths Question + Math Question =");

        question6.setText("Q6: Maths Question + Math Question =");

        ans6.setText("False");

        question7.setText("Q7: Maths Question + Math Question =");

        ans7.setText("True");

        revealbtn.setText("Reveal answers");
        revealbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revealbtnActionPerformed(evt);
            }
        });

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mathsQuizLayout = new javax.swing.GroupLayout(mathsQuiz);
        mathsQuiz.setLayout(mathsQuizLayout);
        mathsQuizLayout.setHorizontalGroup(
            mathsQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mathsQuizLayout.createSequentialGroup()
                .addGroup(mathsQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mathsQuizLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(mathsLabel))
                    .addGroup(mathsQuizLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(question1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ans1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mathsQuizLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(question2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ans2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mathsQuizLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(question3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ans3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mathsQuizLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(question4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ans4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mathsQuizLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(question5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ans5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mathsQuizLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(question6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ans6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mathsQuizLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(question7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ans7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(262, Short.MAX_VALUE))
            .addGroup(mathsQuizLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(revealbtn)
                .addGap(39, 39, 39)
                .addComponent(submitBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        mathsQuizLayout.setVerticalGroup(
            mathsQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mathsQuizLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mathsLabel)
                .addGap(18, 18, 18)
                .addGroup(mathsQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ans1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mathsQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ans2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mathsQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ans3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mathsQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ans4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mathsQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ans5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mathsQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ans6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mathsQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ans7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(mathsQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(revealbtn)
                    .addComponent(resetBtn)
                    .addComponent(submitBtn))
                .addContainerGap())
        );

        jMenu1.setText("File");

        mnuReturn.setText("Return to Math");
        mnuReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReturnActionPerformed(evt);
            }
        });
        jMenu1.add(mnuReturn);

        mnuHome.setText("Main Menu");
        mnuHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHomeActionPerformed(evt);
            }
        });
        jMenu1.add(mnuHome);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        mnuExit.setText("Save & Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu2.add(mnuExit);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mathsQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mathsQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        //get text from textfields

        this.dispose();
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReturnActionPerformed
        new Math().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuReturnActionPerformed

    private void mnuHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHomeActionPerformed
        new appFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuHomeActionPerformed

    private void revealbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revealbtnActionPerformed
        // TODO add your handling code here:
      question1.setText(questions.get(0));
      question2.setText(questions.get(1));
      question3.setText(questions.get(2));
      question4.setText(questions.get(3));
      question5.setText(questions.get(4));
      question6.setText(questions.get(5));
      question7.setText(questions.get(6));
      ans1.setText(answer.get(0));
      ans2.setText(answer.get(1));
      ans3.setText(answer.get(2));
      ans4.setText(answer.get(3));
      ans5.setText(answer.get(4));
      ans6.setText(answer.get(5));
      ans7.setText(answer.get(6));
      
      
      
      
    }//GEN-LAST:event_revealbtnActionPerformed

    private void ans1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ans1ActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        //if (jTextField1.getText().equals(answer.get(0))){
            //marks.add(10);
        
    //}
        
         //if statements to check textfields for correct answers
      if(ans1.getText().equals(answer.get(0))){
          marks.add(10);
      } 
      if(ans2.getText().equals(answer.get(1))){
          marks.add(10);
        }
      if(ans3.getText().equals(answer.get(2))){
        marks.add(10);
      }
      if (ans4.getText().equals(answer.get(3))){
          marks.add(10);
      }
      if (ans5.getText().equals(answer.get(4))){
          marks.add(10);
      }
      if(ans6.getText().equals(answer.get(5))){
          marks.add(10);
      }
      
      if (ans7.getText().equals(answer.get(6))){
          marks.add(10);
      }
      
     for(int i=0;i<marks.size();i++){
        total +=(marks.get(i));
    }
      JOptionPane.showMessageDialog(null,"Your score is"+ total +"/70");
      
       printableTotal = Integer.toString(total);
        
        //Call on class FileIO.java
            FileIO f = new FileIO(name, mark, subj);
            //set the values to the FileIO class
            f.setName(name);
            f.setMarks(mark);
            f.setSubj(subj);
            
            //File IO  write name, subject and mark to the file progress.txt
        //Try catch with exception to catch in case of an error 
        try {
            File fi = new File("outputMath.txt");
            FileWriter fw = new FileWriter(fi);
            BufferedWriter bW = new BufferedWriter(fw);

            bW.write("Your Subject: " + f.getSubj() + ".   ");
            bW.write("Your Name: " + f.getName() + ".   ");
            //bWrite.newLine();
            bW.write("Your Score: " + printableTotal + "/70" + ".  ");
            bW.close();
            JOptionPane.showMessageDialog(null, "Hi " + name + " Your Score and Has been saved to 'your progress' page ");

        } catch (IOException e) {
            System.out.println(e.toString());
            System.out.println("Problem writing to File");
        }
      
    }//GEN-LAST:event_submitBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
       this.dispose();
       new MQuiz().setVisible(true);
    }//GEN-LAST:event_resetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ans1;
    private javax.swing.JTextField ans2;
    private javax.swing.JTextField ans3;
    private javax.swing.JTextField ans4;
    private javax.swing.JTextField ans5;
    private javax.swing.JTextField ans6;
    private javax.swing.JTextField ans7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel mathsLabel;
    private javax.swing.JPanel mathsQuiz;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuHome;
    private javax.swing.JMenuItem mnuReturn;
    private javax.swing.JLabel question1;
    private javax.swing.JLabel question2;
    private javax.swing.JLabel question3;
    private javax.swing.JLabel question4;
    private javax.swing.JLabel question5;
    private javax.swing.JLabel question6;
    private javax.swing.JLabel question7;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton revealbtn;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables

   
}
