/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app1;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author x14517817
 */
public class PQuiz extends javax.swing.JFrame {

    private final ArrayList<Integer> marks;
    private int total;
    private int count;

    private String name;
    private String printableTotal;
    private int mark;
    private String subj;

    /**
     * Creates new form PQuiz
     */
    public PQuiz() {
        initComponents();
        subj = "Physics";
        name = JOptionPane.showInputDialog("Please enter your name");
        marks = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        pquiz = new javax.swing.JLabel();
        question1 = new javax.swing.JLabel();
        question2 = new javax.swing.JLabel();
        question3 = new javax.swing.JLabel();
        question4 = new javax.swing.JLabel();
        question5 = new javax.swing.JLabel();
        question6 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        tbtn1 = new javax.swing.JToggleButton();
        tbtn2 = new javax.swing.JToggleButton();
        tbtn3 = new javax.swing.JToggleButton();
        tbtn4 = new javax.swing.JToggleButton();
        tbtn5 = new javax.swing.JToggleButton();
        tbtn6 = new javax.swing.JToggleButton();
        pQuizMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuReturn = new javax.swing.JMenuItem();
        mnuHome = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Physics Quiz (Sam)");

        pquiz.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pquiz.setForeground(new java.awt.Color(153, 0, 153));
        pquiz.setText("Physics Quiz");

        question1.setText("Q1: At terminal velocity, all motion stops");

        question2.setText("Q2: Your mass on Earth is different than your mass on Mars");

        question3.setText("Q3: Simple machines like pulleys increase the amount of work we can do");

        question4.setText("Q4: Suction is a force");

        question5.setText("Q5: Heat spontaneously flows from a warmer to a colder body");

        question6.setText("Q6: All isotopes are radioactive");

        Submit.setBackground(new java.awt.Color(51, 255, 51));
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Reset.setBackground(new java.awt.Color(255, 0, 0));
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        tbtn1.setText("True/False");
        tbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn1ActionPerformed(evt);
            }
        });

        tbtn2.setText("True/False");
        tbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn2ActionPerformed(evt);
            }
        });

        tbtn3.setText("True/False");
        tbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn3ActionPerformed(evt);
            }
        });

        tbtn4.setText("True/False");
        tbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn4ActionPerformed(evt);
            }
        });

        tbtn5.setText("True/False");
        tbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn5ActionPerformed(evt);
            }
        });

        tbtn6.setText("True/False");
        tbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(question4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(question1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(question2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(question3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(question5, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(question6, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pquiz)
                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tbtn1)
                        .addComponent(tbtn2)
                        .addComponent(tbtn3)
                        .addComponent(tbtn4)
                        .addComponent(tbtn5)
                        .addComponent(tbtn6)))
                .addGap(155, 155, 155))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pquiz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn1)
                    .addComponent(question1))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn2)
                    .addComponent(question2))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn3)
                    .addComponent(question3))
                .addGap(19, 19, 19)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn4)
                    .addComponent(question4))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn5)
                    .addComponent(question5))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn6)
                    .addComponent(question6))
                .addGap(40, 40, 40)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Submit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jMenu1.setText("Go Back");

        mnuReturn.setText("Return to physics");
        mnuReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReturnActionPerformed(evt);
            }
        });
        jMenu1.add(mnuReturn);

        mnuHome.setText("Main Menu");
        mnuHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHomeActionPerformed(evt);
            }
        });
        jMenu1.add(mnuHome);

        pQuizMenuBar.add(jMenu1);

        jMenu2.setText("Exit");

        mnuExit.setText("Save and Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu2.add(mnuExit);

        pQuizMenuBar.add(jMenu2);

        setJMenuBar(pQuizMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReturnActionPerformed
        new Physic().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuReturnActionPerformed

    private void mnuHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHomeActionPerformed
        new appFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuHomeActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_mnuExitActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        if (tbtn1.isEnabled()) {

        } else {
            marks.add(10);
        }
        if (tbtn2.isEnabled()) {

        } else {
            marks.add(10);
        }
        if (tbtn3.isEnabled()) {

        } else {
            marks.add(10);
        }
        if (tbtn4.isEnabled()) {

        } else {
            marks.add(10);
        }
        if (tbtn5.isEnabled()) {
            marks.add(10);
        } else;
        if (tbtn6.isEnabled()) {

        } else {
            marks.add(10);
        }
        for (int i = 0; i < marks.size(); i++) {
            total += (marks.get(i));
        }
        JOptionPane.showMessageDialog(null, "Your score is" + total + "/60");

        printableTotal = Integer.toString(total);

        //Call on class FileIO.java
        FileIO f = new FileIO(name, mark, subj);
        //set the values to the FileIO class
        f.setName(name);
        f.setMarks(mark);
        f.setSubj(subj);

        //File IO  write name, subject and mark to the file progress.txt
        //Try catch with exception to catch in case of an error 
        try {
            File fi = new File("outputPhysics.txt");
            FileWriter fw = new FileWriter(fi);
            BufferedWriter bW = new BufferedWriter(fw);

            bW.write("Your Subject: " + f.getSubj() + ".   ");
            bW.write("Your Name: " + f.getName() + ".   ");
            //bWrite.newLine();
            bW.write("Your Score: " + printableTotal + "/60" + ".  ");
            bW.close();
            JOptionPane.showMessageDialog(null, "Hi " + name + " Your Score and Has been saved to 'your progress' page ");

        } catch (IOException e) {
            System.out.println(e.toString());
            System.out.println("Problem writing to File");
        }
    }//GEN-LAST:event_SubmitActionPerformed

    private void tbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn1ActionPerformed
//        if(tbtn1.isEnabled()){
//            
//        }else marks.add(10);
    }//GEN-LAST:event_tbtn1ActionPerformed

    private void tbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn2ActionPerformed
//        if(tbtn2.isEnabled()){
//            
//        }else marks.add(10);
    }//GEN-LAST:event_tbtn2ActionPerformed

    private void tbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn3ActionPerformed
//        if(tbtn3.isEnabled()){
//           
//        }else marks.add(10);
//        
    }//GEN-LAST:event_tbtn3ActionPerformed

    private void tbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn4ActionPerformed
//       if(tbtn4.isEnabled()){
//           
//         }else marks.add(10);

    }//GEN-LAST:event_tbtn4ActionPerformed

    private void tbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn5ActionPerformed
//        if(tbtn5.isEnabled()){
//            marks.add(10);
//         }else;
//        
    }//GEN-LAST:event_tbtn5ActionPerformed

    private void tbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn6ActionPerformed
//        if(tbtn6.isEnabled()){
//            
//        }else marks.add(10);

    }//GEN-LAST:event_tbtn6ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        new PQuiz().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JButton Submit;
    private javax.swing.JPanel background;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuHome;
    private javax.swing.JMenuItem mnuReturn;
    private javax.swing.JMenuBar pQuizMenuBar;
    private javax.swing.JLabel pquiz;
    private javax.swing.JLabel question1;
    private javax.swing.JLabel question2;
    private javax.swing.JLabel question3;
    private javax.swing.JLabel question4;
    private javax.swing.JLabel question5;
    private javax.swing.JLabel question6;
    private javax.swing.JToggleButton tbtn1;
    private javax.swing.JToggleButton tbtn2;
    private javax.swing.JToggleButton tbtn3;
    private javax.swing.JToggleButton tbtn4;
    private javax.swing.JToggleButton tbtn5;
    private javax.swing.JToggleButton tbtn6;
    // End of variables declaration//GEN-END:variables

    private void setAOne(String aOne) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setATwo(String aTwo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setAThree(String aThree) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setAFour(String aFour) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setAFive(String aFive) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setASix(String aSix) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
